### ISSUE TITLE
Feature Request: Multiple bundle categories

### ISSUE THREAD

**Issue by ErikKoppenhagen** [OpenKieler/osgiviz#8] opened 2020-01-24 13:44 UTC
Some bundles may have more than one category, separated by commas. At the moment, this is interpreted as one bundle category (e.g. "_protocol,base,app_")

The categories should be split correctly and the bundles should be shown in each of the categories.

**Comment by NiklasRentzCAU** [comment] 2020-01-30 10:01
This is caused by some bug in the model generator. Either I will have a look at it in the future or @niratschi might have a look at it.
Anyway, blocked by #10.

**Comment by NiklasRentzCAU** [comment] 2020-03-13 12:44
Fixed with #20.

**Closed by NiklasRentzCAU** 2020-03-13 12:44 UTC
